### PR TITLE
Fix Uno MajorTrouble_Flags.__str__ AttributeError freezing 5 partition sensors

### LINKED ISSUE #251: Uno: MajorTrouble_Flags.__str__ typo crashes handle_partition_trouble_state_change, freezing 5 partition sensors
## Summary

On Uno panels, `handle_partition_trouble_state_change` raises `AttributeError` on **every** invocation due to a one-character typo in `MajorTrouble_Flags.__str__`. The exception is raised before any status fields are assigned, so five partition binary sensors never update from their defaults for the entire lifetime of the integration.

Present in `main` and in `v1.2.1`.

## Symptom

```
WARNING (MainThread) [custom_components.envisalink_new.pyenvisalink.envisalink_base_client]
Error in handle_partition_trouble_state_change for code '%06' data '0000000000000000':
AttributeError: 'MajorTrouble_Flags' object has no attribute 'wireless_device_low_Battery'
```

## Root cause

`pyenvisalink/uno_envisalinkdefs.py` — the bitfield declares the field in lowercase (line 16), but `__str__` references it with a capital `B` (line 38):

```python
class MajorTrouble_Bitfield(ctypes.LittleEndianStructure):
    _fields_ = [
        ...
        ("wireless_device_low_battery", c_uint8, 1),   # line 16 — lowercase
        ...
    ]

class MajorTrouble_Flags(ctypes.Union):
    def __str__(self) -> str:
        return (
            ...
            f" wireless_device_low_Battery={self.wireless_device_low_Battery}"  # line 38 — capital B
            ...
        )
```

This was introduced in 3a31edfd ("Add zone low battery binary sensor", #214). That commit renamed the bitfield member from `wireless_device_low_Battery` to `wireless_device_low_battery` but did not update the corresponding reference in `__str__`:

```diff
-        ("wireless_device_low_Battery", c_uint8, 1),
+        ("wireless_device_low_battery", c_uint8, 1),
```

Every other line in `__str__` matches its field; only this one was missed.

## Why it breaks state updates rather than just logging

In `pyenvisalink/uno_client.py`, the failing interpolation happens on line 148 — *before* any of the status assignments:

```python
def handle_partition_trouble_state_change(self, code, data):
    partition_updates = []
    for currentIndex in range(0, 8):
        ...
        _LOGGER.debug(f'Partition {partitionNumber} has new trouble state {flags}')  # line 148 — raises here

        status = self._alarmPanel.alarm_state['partition'][partitionNumber]['status']
        status['trouble'] = bool(flags.service_required)              # line 151 — never reached
        status['ac_present'] = not bool(flags.ac_failure)             # line 152
        status['bat_trouble'] = bool(flags.system_battery_overcurrent) # line 153
        status['bell_trouble'] = bool(flags.system_bell_fault)         # line 154
        status['zone_low_battery'] = bool(flags.wireless_device_low_battery)  # line 155
```

Two things make this worse than a debug-only issue:

1. The f-string is built **eagerly**, so the exception fires regardless of configured log level — setting the logger above DEBUG does not avoid it.
2. `envisalink_base_client.py` catches it and `continue`s, so `result` is never returned and the `state_change` callbacks never fire:

```python
result = handlerFunc(cmd["code"], cmd["data"])          # raises
if result and cmd.get("state_change"):                  # never reached
    self.handle_state_change_callbacks(result)
except Exception as err:
    _LOGGER.warning("Error in %s for code '%s' data '%s': %s: %s", ...)
    continue
```

## Impact

These five partition binary sensors are permanently stuck at their `alarm_state.py` defaults on Uno panels:

| Sensor | Status field | Stuck at |
|---|---|---|
| AC Power | `ac_present` | `on` |
| Panel Health | `trouble` | `off` |
| Panel Battery | `bat_trouble` | `off` |
| System Bell | `bell_trouble` | `off` |
| Zone Batteries | `zone_low_battery` | `off` |

Notably, the AC Power sensor reporting a permanent `on` means automations that alert on utility power loss can never fire — the failure is silent, since a sensor that is correctly `on` and one that is never written look identical in the UI and in history.

Also worth flagging: the zone-low-battery sensor added by #214 has never functioned on Uno panels as a result of this.

## Uno-specific

DSC is unaffected — it derives low battery from alpha/zone status codes in `dsc_envisalinkdefs.py`, not from `MajorTrouble_Flags`.

There is also no fallback path on Uno. `HoneywellClient.handle_keypad_update` independently writes `ac_present`, but `UnoClient` disables it:

```python
def handle_keypad_update(self, code, data):
    return None
```

So on Uno, the crashing trouble handler is the only writer of `ac_present`.

## Fix

`pyenvisalink/uno_envisalinkdefs.py`, line 38:

```diff
-            f" wireless_device_low_Battery={self.wireless_device_low_Battery}"
+            f" wireless_device_low_battery={self.wireless_device_low_battery}"
```

Happy to open a PR if that's useful.

### PR DESCRIPTION
**Pull request by shmookles**
## What

One-character fix: `MajorTrouble_Flags.__str__` referenced `wireless_device_low_Battery` (capital B) while the `MajorTrouble_Bitfield` field is declared `wireless_device_low_battery`.

```diff
-            f" wireless_device_low_Battery={self.wireless_device_low_Battery}"
+            f" wireless_device_low_battery={self.wireless_device_low_battery}"
```

## Why it matters

The mismatch was introduced in 3a31edf (#214), which renamed the bitfield member to lowercase but left the `__str__` reference capitalized.

On Uno panels, `handle_partition_trouble_state_change` logs the flags via an f-string **before** any status assignments:

```python
_LOGGER.debug(f'Partition {partitionNumber} has new trouble state {flags}')  # raises AttributeError here
status['trouble'] = ...          # never reached
status['ac_present'] = ...
status['bat_trouble'] = ...
status['bell_trouble'] = ...
status['zone_low_battery'] = ...
```

The f-string is built eagerly regardless of log level, so every partition trouble update (`%06`) raised `AttributeError`, which the handler loop in `envisalink_base_client` caught and `continue`d — so no status was written and no state-change callback fired. Five Uno partition sensors were permanently stuck at their defaults: `ac_present` (AC Power stuck on), `trouble`, `bat_trouble`, `bell_trouble`, and `zone_low_battery` — the last being the sensor #214 set out to add.

DSC is unaffected (it derives low battery from alpha/zone codes, not `MajorTrouble_Flags`), and Uno has no fallback since `UnoClient.handle_keypad_update` returns `None`.

## Testing

Reproduced the observed log error, then confirmed the patched `__str__` renders without raising and reads the low-battery bit correctly:

```
str() -> 0x04 service_required=0 ac_failure=0 wireless_device_low_battery=1 ...
```

Closes #251

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by shmookles** [comment]
Confirmed on a live Uno panel (EnvisaLink).

Before the patch, every restart logged this at startup — Uno login issues an `InitialStateDump`, which makes the panel send a `%06` partition trouble update:

```
WARNING [custom_components.envisalink_new.pyenvisalink.envisalink_base_client]
Error in handle_partition_trouble_state_change for code '%06' data '0000000000000000':
AttributeError: 'MajorTrouble_Flags' object has no attribute 'wireless_device_low_Battery'
```

After applying this fix and restarting, the same startup `%06` processes with **no error**, and the five partition trouble sensors (`ac_present`, `trouble`, `bat_trouble`, `bell_trouble`, `zone_low_battery`) now update from the panel instead of staying frozen at their defaults.
